### ISSUE TITLE
Is App Engine app/project required?

### ISSUE THREAD

**Issue by Zhong-z** [keypup-io/cloudtasker#30]
Trying to create default queue from gcloud CLI and got the following errors. 

> There is no App Engine app in project [xxx].
> 
> Would you like to create one (y/N)?  n
> 
> ERROR: (gcloud.tasks.queues.create) Could not determine the location for the project. Please try again. It is possible an AppEngine App does not exist for this project.

Wondering if I missed anything during setup? Is App Engine app required to use Cloud Tasks? My web app is a Cloud Run service.

**Comment by alachaum** [comment]
Hi @Zhong-z 

To be honest I never noticed that requirement because we already had an App Engine project on our account.

According to their get started guide it's required: https://cloud.google.com/tasks/docs/quickstart#add_a_task_to_the_cloud_tasks_queue

They also mention it being a requirement in their "create a queue" article:
https://cloud.google.com/tasks/docs/creating-queues

**Comment by Zhong-z** [comment]
Thanks @alachaum
