### ISSUE TITLE
Any chance of persisting cron in the database

### ISSUE THREAD

**Issue by matthewford** [keypup-io/cloudtasker#35]
Having a hard time getting cloud sql and cloud redis to both be available via cloud run/build it seems like if you add a vpc to connect redis you loose cloud sql connection.

Would you be open to a option to store cron config in Postgres?

**Comment by alachaum** [comment]
Hi @matthewford , I'm not really keen on adding more infrastructure dependencies to the library to be honest. I try to limit them to what Sidekiq requires so that people can easily migrate from Sidekiq to Cloudtasker when they move to Cloud Run. I had to rework cron, I would rather support Google Cron Scheduler.

Now you're saying you're struggling with VPC connections. I'm a bit surprise you're hitting this issue. Would [this article on GCP deployment](https://www.keypup.io/blog/deploying-production-rails-applications-to-gcp) help? I wrote it a while ago. 

For the Cloud SQL connection, you can use a native IP connection via your VPC. See [this article](https://www.keypup.io/blog/cloud-run-and-cloud-sql-avoid-hitting-cloud-sql-admin-connection-quota) which explains how to do so.

**Comment by matthewford** [comment]
Thanks got the VPC working
