### ISSUE TITLE
grpc cannot be used before and after forking with `deliver_later`

### ISSUE THREAD

**Issue by matthewford** [keypup-io/cloudtasker#44]
Hi, 

We're running into an issue with deliver_later where this error is thrown.

grcp cannot be used before and after forking

Anyone seen this before?

Thanks,
Matt

**Comment by matthewford** [comment]
is the issue possibly scheduling another job from within a job?

**Comment by alachaum** [comment]
@matthewford I have never seen this issue actually. I don't believe it relates to Cloudtasker considering grcp is not part of the dependency tree (check the [Gemfile.lock](https://github.com/keypup-io/cloudtasker/blob/master/examples/rails/Gemfile.lock) for the Rails Example).

However I see that there was one grcp issue fixed in 2018 related to this error:
- Issue: https://github.com/grpc/grpc/issues/7951
- PR: https://github.com/grpc/grpc/pull/16332

From there can you 1) try to upgrade grcp and 2) track down which gem in your build uses grcp and 3) check how this gem is used?

**Comment by dreamfall** [comment]
@alachaum hey,

gRPC is used by grpc-google-iam-v1 that's used by google-cloud-tasks 1.5.1. That's the latest version cloudtasker allows with google-cloud-tasks. 

PR you mentioned actually raises the error, not fixes it (it was hanging the process before).

Perhaps we can try to upgrade google-cloud-tasks to 2.2? How complicated this update would be?

**Comment by alachaum** [comment]
Searched for gr**c**p instead of gr**p**c in the Gemfile.lock 🤦 (renamed the issue title to avoid future confusion). Anyway, definitely related to cloudtasker.

Migrating to google-cloud-tasks `v2.2` is not that complicated I believe. Ideally we should maintain backward compatibility - which means discovering which version of google-cloud-tasks is installed and using the [right adapter](https://github.com/keypup-io/cloudtasker/tree/master/lib/cloudtasker/backend) based on that. I don't much time on my side to do it at the moment unfortunately.

Question is: are we sure this upgrade is going to fix the issue? Do we know what is causing it in the first place?

**Comment by matthewford** [comment]
Looking at the issue further I'm not sure if upgrading will fix the issue, as it mentions they will not fix the issue with treads.
