### ISSUE TITLE
Post-install message from google-gax

### ISSUE THREAD

**Issue by alfie-max** [keypup-io/cloudtasker#55]
Getting this as soon as i install the gem

```
Post-install message from google-gax:
*******************************************************************************
The google-gax gem is officially end-of-life and will not be updated further.

If your app uses the google-gax gem, it likely is using obsolete versions of
some Google Cloud client library (google-cloud-*) gem that depends on it. We
recommend updating any such libraries that depend on google-gax. Modern Google
Cloud client libraries will depend on the gapic-common gem instead.
*******************************************************************************
```

what does this mean.. and what effects could this have for this gem in the future..

**Comment by alachaum** [comment]
Hi @alfie-max , the current stable version of Cloudtasker is still using google-cloud-tasks `v1`, which relies on a now deprecated version of google-gax.

This will be fixed in cloudtasker `v0.13`, which uses google-cloud-tasks v2 and adds support for Ruby 3.

If you want to make the switch now you can put the following in your Gemfile:
```
gem 'cloudtasker', '~> 0.13.rc2'
```

I'll update this issue once `v0.13` is officially out.

**Comment by alfie-max** [comment]
Right.. i saw these.. but I’m not on ruby 3

**Comment by alachaum** [comment]
Don't worry, `v0.13` supports Ruby 2 **and** Ruby 3

**Comment by alachaum** [comment]
Cloudtasker `v0.13.0` has been released. The message should not appear anymore.
